config/urls.py
from django.contrib import admin
from django.urls import path, include # new code
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls'), name='post'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT) 

post/urls.py
from django.urls import path
from .views import list_view, detail_view, post_share, contact_view, about_view

app_name = "post"

urlpatterns = [
	path('about/',about_view, name="about"),
	path('contact/',contact_view, name="contact"),
	path('<int:id>/share/', post_share, name="post_share"),
	path('<int:id>/<slug:slug>/', detail_view, name='post_detail'),
	path('', list_view, name='post_list'),
]

post/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone # new code
from autoslug import AutoSlugField
from ckeditor.fields import RichTextField

from django.urls import reverse # new code

STATUS = (
	('active','Chop_etildi'),
	('deactive','Qoralama')
)


# Create your models here.

class PublishMeneger(models.Manager): # new code
	def get_queryaet(self):
		return super().get_queryaet.filter(status='active')


class Post(models.Model):
	title = models.CharField(max_length=250, verbose_name="Sarlavha" )
	slug = AutoSlugField(populate_from="title")
	body = RichTextField(verbose_name="Matn")
	photo = models.ImageField(upload_to='post_photo/%Y/%m/%d/', verbose_name="Rasm")
	see = models.PositiveIntegerField(blank=True, null=True, verbose_name="Ko'rishlar soni")
	publish = models.DateTimeField(default=timezone.now, verbose_name="chop etilgan vaqt")
	status  = models.CharField(max_length=100, choices=STATUS, verbose_name="Holati")

	created_at = models.DateTimeField(auto_now_add=True, verbose_name="yaratilgan vaqti")
	updated = models.DateTimeField(auto_now=True, verbose_name="tahrirlangan vaqti")
	created_by = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Muallif")

	objects = models.Manager()
	published = PublishMeneger()


	class Meta:
		ordering = ('-publish',)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('post:post_detail', args=[self.id, self.slug])

	


class Comment(models.Model):
	post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
	name = models.CharField(max_length=150)
	email = models.EmailField()
	body = RichTextField()
	created_at = models.DateTimeField(auto_now=True)
	active = models.BooleanField(default=True)

	class Meta:
		ordering = ('-created_at',)

	def __str__(self):
		return self.name

post/forms.py
from django import forms
from .models import Comment

class PostShareForm(forms.Form):
	name = forms.CharField(max_length=70)
	email = forms.EmailField()
	to  = forms.EmailField()
	comment = forms.CharField(required=False)


class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ('name','email','body')
		

post/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import PostShareForm, CommentForm
from django.core.mail import send_mail


def list_view(request):
	posts = Post.objects.filter(status='active')

	# pageinator ---------------------------------->>>>
	paginator = Paginator(posts, 3)
	page = request.GET.get('page')
	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
		posts = paginator.page(1)
	except EmptyPage:
		posts = paginator.page(paginator.num_pages)
	# pageinator ---------------------------------->>>>
	
	return render(request, 'post/list.html', {'posts':posts, "page":page})

def detail_view(request,id, slug):
	post = get_object_or_404(Post, id=id, slug=slug)
	
	# activ commentlar "comments" o'zgaruvchisiga yig'ib olinadi
	comments = post.comments.filter(active=True)
	new_comment = None
	if request.method == 'POST':
		# Foydalanuvchi uchun izoh qoldirish formasi ko'rinadi
		comment_form = CommentForm(data=request.POST)
		if comment_form.is_valid():
			# Biz comment yaratamiz, lekin uni hali ma'lumotlar bazasida saqlamaymiz
			new_comment = comment_form.save(commit=False)
			# Joriy maqolaga sharh qo'shish.
			new_comment.post = post
			# commentni malumotlar bazasiga saqlaymiz 
			new_comment.save()
	else:
		comment_form = CommentForm()

	context = {'post':post,
			'comments':comments,
			'new_comment':new_comment,
			'comment_form':comment_form,
			}

	return render(request, 'post/detail.html', context)

def post_share(request, id):
	# id bo'yicha maqola olinadi
	post = get_object_or_404(Post, id=id)
	sent = False
	if request.method == 'POST':
		# forma saqlash  uchun yuboriladi
		form = PostShareForm(request.POST)
		if form.is_valid():
			# barcha maydonlar tasdiqlandi
			cd = form.cleaned_data
			
			post_url = request.build_absolute_uri(post.get_absolute_url())
			email = cd['email']
			subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title)
			message = 'Read "{}" at {}\n\n{}\'s comment:{}'.format(post.title, post_url, cd['name'], cd['comment'])
			send_mail(subject, message, email, [cd['to']])
			sent = True
	else:
		form = PostShareForm()

	context = {'post': post, 'form': form, 'sent': sent}

	return render(request, 'post/share.html', context)

def about_view(request):
	return render(request,'about.html')

def contact_view(request):
	return render(request,'contact.html')

templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<body id="top">

	<section class="section team">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-lg-12">
					<div class="section-title text-center">
						<h2 class="mb-4">Biz haqimizda</h2>
						<div class="divider mx-auto my-4"></div>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus aliquet nibh commodo nisi posuere lobortis. Sed molestie est eu urna cursus rutrum. In mattis pellentesque sapien in ullamcorper. Integer quis dapibus orci, id iaculis metus. Nulla vitae placerat tellus, ut scelerisque justo. Vivamus lacinia euismod massa sit amet laoreet. Donec sem lorem, congue eget tristique et, commodo a nunc. Mauris varius condimentum nisi, id consequat purus dignissim nec. Sed leo metus, rutrum in neque quis, rhoncus porttitor diam. Sed venenatis quis eros et tempor. Quisque eget efficitur lorem, id cursus nibh.

						Pellentesque in mattis massa. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed vehicula placerat auctor. Aliquam malesuada est turpis, vel sodales orci tempor placerat. Vivamus bibendum vel lacus nec congue. Phasellus et accumsan nisi. Aenean maximus pulvinar tortor, ac malesuada massa hendrerit at. Donec aliquet augue facilisis ante volutpat varius et sed ex. Mauris malesuada aliquam lobortis. Maecenas semper nisl elit, eu sodales augue faucibus eu. Suspendisse consectetur arcu ut nisi elementum congue. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam pharetra ac magna ac finibus. Donec ultrices accumsan neque, in egestas ante egestas porta.
						</p><br>
						<h4>Lorem ipsum</h4>
						<p>

						Vestibulum condimentum libero at tempor lacinia. Donec cursus suscipit orci, et rhoncus ligula mollis nec. Sed pharetra pretium tortor, non tristique orci faucibus quis. Integer vitae magna blandit, euismod urna vitae, euismod eros. Duis nec elementum ipsum, non ullamcorper lacus. Donec convallis neque cursus odio imperdiet feugiat quis quis mi. Cras id erat volutpat, laoreet nisi at, efficitur urna. Duis libero lectus, vestibulum eget nulla in, tristique gravida ipsum. Morbi a tempus ante, at mattis tellus. Duis ante purus, eleifend quis placerat vel, sollicitudin sollicitudin metus. Aliquam erat volutpat. Proin eu nisl sed odio cursus faucibus.

						Cras sit amet mattis neque, et malesuada nisl. Ut auctor ex lobortis porta semper. Cras purus enim, tempor non purus vitae, sollicitudin ultricies odio. Vivamus tristique purus vitae rutrum eleifend. Ut molestie tellus nulla, posuere interdum dolor lacinia eget. Etiam a ligula eget ex tempus interdum. Interdum et malesuada fames ac ante ipsum primis in faucibus. In ornare neque nunc, in tristique ante luctus vel. Aliquam luctus lorem a varius molestie.

						Aliquam volutpat, mi a sollicitudin tempor, augue tellus aliquet nibh, eget faucibus massa augue at ligula. Morbi aliquet purus non cursus lobortis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nunc eu justo sit amet dolor ornare rutrum id et mi. Etiam ex quam, iaculis ac aliquam interdum, venenatis quis mauris. Cras fermentum eu ipsum id dapibus. Aenean commodo tortor convallis venenatis lacinia. Maecenas ex nisl, fermentum vel libero sit amet, vehicula facilisis tellus. Maecenas a enim a lectus porta pretium ac vitae risus. Nunc vehicula purus ullamcorper, sodales lectus vitae, elementum diam. Mauris porttitor luctus accumsan. Sed non aliquet metus.
						</p><br>
						<h4>Lorem ipsum</h4>
						<p>
						Mauris tortor erat, vestibulum in aliquam molestie, aliquam a enim. Cras eu interdum nunc, at mattis augue. Integer scelerisque ornare nulla. Donec dapibus quam sit amet ligula auctor, sit amet aliquet ante fermentum. Vestibulum pellentesque feugiat erat, eget luctus orci vehicula nec. Integer mollis in quam vel luctus. Nulla commodo neque ipsum, id porta mauris gravida eget. Donec mattis turpis sit amet justo egestas accumsan id in magna. Ut luctus est eu porta fringilla. Praesent lacinia enim vitae pretium molestie. Praesent sit amet arcu finibus, facilisis nunc nec, elementum ex. In dolor nisl, fringilla vitae ultricies sed, sollicitudin in nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Proin accumsan ut eros eu pharetra. Fusce mattis, enim sed lacinia dignissim, est tortor lacinia velit, pretium aliquet nibh dui et tortor.
						</p><br>
						<h4>Lorem ipsum</h4>
						<p>
						Nullam condimentum sodales ligula id ullamcorper. Duis iaculis malesuada dui eu fermentum. Vivamus vel gravida nisl. Quisque vehicula, sapien sed suscipit faucibus, dui nisi scelerisque justo, at suscipit erat justo a risus. Praesent at ante elementum arcu molestie sodales at vitae risus. Nullam posuere mollis convallis. Nulla pretium egestas lacus in mattis. Suspendisse elementum nec lorem quis suscipit. Sed nec accumsan nunc. Phasellus lobortis, libero non vestibulum auctor, tortor risus vulputate eros, a consequat ex mi non nulla. Curabitur commodo commodo elit a luctus. Quisque luctus sit amet turpis ac pretium. Duis non consectetur augue, at tristique purus. In hac habitasse platea dictumst. Integer sed pretium erat. Nunc magna dolor, pulvinar quis sollicitudin nec, efficitur non lacus.

						Quisque dui erat, viverra vitae porta sed, condimentum eu diam. Aenean commodo molestie magna ac pulvinar. Duis ut nulla velit. Integer vel arcu ante. Aenean varius dolor odio, non gravida tellus scelerisque eget. Aenean sit amet ipsum a neque mollis facilisis a at leo. Vestibulum gravida magna dictum gravida efficitur. Donec pulvinar lacus et nisi malesuada, id rhoncus nulla laoreet. Nullam hendrerit urna sit amet ligula vulputate laoreet. Aliquam sagittis volutpat cursus. Curabitur nec enim eget augue porta semper. Suspendisse viverra neque felis, rutrum laoreet tellus bibendum quis. Nam facilisis enim velit, vitae laoreet nunc posuere sit amet. Cras vel aliquam dui.

						Sed eros eros, ultricies id tincidunt in, ultrices quis purus. Etiam et lorem ut est ultrices consequat a quis nunc. Quisque non semper magna. Nulla hendrerit dolor nec est varius, eget eleifend tellus cursus. Nullam ultrices vulputate nulla, bibendum suscipit nisi feugiat laoreet. Sed eget mattis elit. Phasellus feugiat diam erat, ut finibus nisi fringilla at. Sed vitae facilisis justo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam consectetur quis arcu vitae suscipit. Aliquam lacinia turpis sem, eu sagittis nibh pretium scelerisque. Integer semper, dui eu tempor mollis, eros ante placerat urna, a volutpat ligula mi non sapien. Nam sagittis leo et aliquet blandit.

						Pellentesque accumsan efficitur cursus. Etiam accumsan dignissim lacinia. Nulla in turpis vitae urna sagittis sagittis. Sed molestie elit in aliquam gravida. Mauris risus orci, pretium eget ex at, tincidunt molestie tortor. Aliquam molestie, leo convallis consectetur bibendum, orci ligula aliquet odio, id sodales augue dui porttitor ex. Nullam ullamcorper nisi ac turpis cursus finibus.

						Generated 10 paragraphs, 983 words, 6604 bytes of Lorem Ipsum</p>
					</div>
				</div>
			</div>
		</div>
	</section>

</body>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
{% load static %}


<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<title>{% block title %} {% endblock title %}</title>
		
		<link rel="shortcut icon" type="image/x-icon" href="{% static '/images/favicon.ico' %}" />
		<!-- bootstrap.min css -->
		<link rel="stylesheet" href="{% static 'plugins/bootstrap/css/bootstrap.min.css' %}">
		<!-- Icon Font Css -->
		<link rel="stylesheet" href="{% static 'plugins/icofont/icofont.min.css' %}">
		<!-- Slick Slider  CSS -->
		<link rel="stylesheet" href="{% static 'plugins/slick-carousel/slick/slick.css' %}">
		<link rel="stylesheet" href="{% static 'plugins/slick-carousel/slick/slick-theme.css' %}">		
		<!-- Main Stylesheet -->
		<link rel="stylesheet" href="{% static 'css/style.css' %}">
		<link rel="stylesheet" href="{% static 'css/main.css' %}">
		

	</head>
	<body>
		<header>
			<div class="header-top-bar">
				<div class="container">
					<div class="row align-items-center">
						<div class="col-lg-6">
							<ul class="top-bar-info list-inline-item pl-0 mb-0">
								<li class="list-inline-item"><a href="mailto:support@gmail.com"><i class="icofont-support-faq mr-2"></i>test@gmail.com</a></li>
								<li class="list-inline-item"><i class="icofont-location-pin mr-2"></i>Manzil Ta-134/A, Namangan, Uzbekistan </li>
							</ul>
						</div>
						<div class="col-lg-6">
							<div class="text-lg-right top-right-bar mt-2 mt-lg-0">
								<a href="tel:+23-345-67890" >
									<span>Tel : </span>
									<span class="h4">+99894 308-99-79 </span>
								</a>
							</div>
						</div>
					</div>
				</div>
			</div>
			<nav class="navbar navbar-expand-lg navigation" id="navbar">
				<div class="container">
				 	 <a class="navbar-brand" href="index.html">
					  	<img src="{% static 'images/logo.png' %}" alt="" class="img-fluid">
					  </a>

				  	<button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarmain" aria-controls="navbarmain" aria-expanded="false" aria-label="Toggle navigation">
					<span class="icofont-navigation-menu"></span>
				  </button>
			  
				  <div class="collapse navbar-collapse" id="navbarmain">
					<ul class="navbar-nav ml-auto">
					  <li class="nav-item active">
						<a class="nav-link" href="{% url 'post:post_list' %}">Home</a>
					  </li>
					   <li class="nav-item"><a class="nav-link" href="{% url 'post:about' %}">About</a></li>
					   <li class="nav-item"><a class="nav-link" href="{% url 'post:contact' %}">Contact</a></li>
					</ul>
				  </div>
				</div>
			</nav>			
		</header>

		{% block content %}

		{% endblock content %}

		<footer class="footer section gray-bg">
			<div class="container">
				<div class="row">
					<div class="col-lg-4 mr-auto col-sm-6">
						<div class="widget mb-5 mb-lg-0">
							<div class="logo mb-4">
								<img src="images/logo.png" alt="" class="img-fluid">
							</div>
							<p>Ushbu sayt O'zbekiston  va jaxondagi eng so'ngi turli mavzulardagi yangiliklardan birinchilardan bo'lib sini habardor qilib turadi.</p>
							<p>Doim biz bilan birga bo'ling va bizni ijtimoiy tarmoqlarda ham kuzatib boring</p>

							<ul class="list-inline footer-socials mt-4">
								<li class="list-inline-item"><a href="https://www.facebook.com/themefisher"><i class="icofont-facebook"></i></a></li>
								<li class="list-inline-item"><a href="https://twitter.com/themefisher"><i class="icofont-twitter"></i></a></li>
								<li class="list-inline-item"><a href="https://www.pinterest.com/themefisher/"><i class="icofont-linkedin"></i></a></li>
							</ul>
						</div>
					</div>

					<div class="col-lg-2 col-md-6 col-sm-6">
						<div class="widget mb-5 mb-lg-0">
							<h4 class="text-capitalize mb-3">Yo'nalishlar</h4>
							<div class="divider mb-4"></div>

							<ul class="list-unstyled footer-menu lh-35">
								<li><a href="#">Siyosat </a></li>
								<li><a href="#">Dunyo</a></li>
								<li><a href="#">Sport</a></li>
								<li><a href="#">Sog'liqni saqlash</a></li>
								<li><a href="#">Ta'lim</a></li>
								<li><a href="#">San'at</a></li>
								<li><a href="#">Madaniyat</a></li>
							</ul>
						</div>
					</div>

					<div class="col-lg-2 col-md-6 col-sm-6">
						<div class="widget mb-5 mb-lg-0">
							<h4 class="text-capitalize mb-3">Qo'llab-quvvatlash</h4>
							<div class="divider mb-4"></div>

							<ul class="list-unstyled footer-menu lh-35">
								<li><a href="#">Terms & Conditions</a></li>
								<li><a href="#">Xafsizlik va ishonchlilik</a></li>
								<li><a href="#">Kompania bilan aloqa </a></li>
								<li><a href="#">FAQ</a></li>
								<li><a href="#">Kompaniya huquqlari</a></li>
							</ul>
						</div>
					</div>

					<div class="col-lg-3 col-md-6 col-sm-6">
						<div class="widget widget-contact mb-5 mb-lg-0">
							<h4 class="text-capitalize mb-3">Aloqa</h4>
							<div class="divider mb-4"></div>

							<div class="footer-contact-block mb-4">
								<div class="icon d-flex align-items-center">
									<i class="icofont-email mr-3"></i>
									<span class="h6 mb-0">Qo'llab quvvatlash 24/7</span>
								</div>
								<h4 class="mt-2"><a href="tel:+23-345-67890">Support@email.com</a></h4>
							</div>

							<div class="footer-contact-block">
								<div class="icon d-flex align-items-center">
									<i class="icofont-support mr-3"></i>
									<span class="h6 mb-0">Mon to Fri : 08:30 - 18:00</span>
								</div>
								<h4 class="mt-2"><a href="tel:+23-345-67890">1023</a></h4>
							</div>
						</div>
					</div>
				</div>
				
				<div class="footer-btm py-4 mt-5">
					<div class="row align-items-center justify-content-between">
						<div class="col-lg-6">
							<div class="copyright">
								&copy; Copyright Reserved to by <a href="https://t.me/Asadbek9979" target="_blank">Fayzullayev Asadbek </a>
							</div>
						</div>
					</div>

					<div class="row">
						<div class="col-lg-4">
							<a class="backtop js-scroll-trigger" href="#top">
								<i class="icofont-long-arrow-up"></i>
							</a>
						</div>
					</div>
				</div>
			</div>
		</footer>
		<!-- Essential Scripts =====================================-->

	    <!-- Main jQuery -->
	    <script src="{% static 'plugins/jquery/jquery.js' %}"></script>
	    <!-- Bootstrap 4.3.2 -->
	    <script src="{% static 'plugins/bootstrap/js/popper.js' %}"></script>
	    <script src="{% static 'plugins/bootstrap/js/bootstrap.min.js' %}"></script>
	    <script src="{% static 'plugins/counterup/jquery.easing.js' %}"></script>
	    <!-- Slick Slider -->
	    <script src="{% static 'plugins/slick-carousel/slick/slick.min.js' %}"></script>
	    <!-- Counterup -->
	    <script src="{% static 'plugins/counterup/jquery.waypoints.min.js' %}"></script>
	    
	    <script src="{% static 'plugins/shuffle/shuffle.min.js' %}"></script>
	    <script src="{% static 'plugins/counterup/jquery.counterup.min.js' %}"></script>
	
	    <script src="{% static 'js/script.js' %}"></script>
	    <script src="{% static 'js/contact.js' %}"></script>

	    <!-- faveicon 	 -->
	    <script src="https://kit.fontawesome.com/ef8355979e.js" crossorigin="anonymous"></script>

	</body>
</html>

templates/paginator.html
<div class="btn-group" role="group" aria-label="Basic outlined example" style="text-align: center;">

    {% if page.has_previous %}
        <button type="button" class="btn btn-outline-primary"><a style="color:black;" href="?page={{page.previous_page_number}}">Ortga</a></button>
    {% endif %}

    <button type="button" class="btn btn-outline-primary">{{ page.number }}</button>
    
    {% if page.has_next %}
        <button type="button" class="btn btn-outline-primary" ><a style="color:black;" href="?page={{ page.next_page_number }}">Keyingisi</a></button>
    {% endif %}

</div>

templates/post/detail.html
{% extends 'base.html' %}
{% load blog_tags %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<section class="section blog-wrap">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="row">
					<div class="col-lg-12 mb-5">
						<div class="single-blog-item">
							<img src="{{ post.photo.url }}" alt="" class="img-fluid">

							<div class="blog-item-content mt-5">
								<div class="blog-item-meta mb-3">
									<span class="text-black text-capitalize mr-3"><i class="fa-solid fa-user"></i>{{ post.created_by }}</span>
									<span class="text-black text-capitalize mr-3"><i class="icofont-calendar mr-2"></i>{{ post.created_at |date:"d.m.Y | f" }}</span>
									<span class="text-muted text-capitalize mr-3"><i class="icofont-comment mr-2"></i>{{ comments.count }}</span>
								</div> 

								<h2 class="mb-4 text-md">{{ post.title }}</h2>

								<p class="lead mb-4">{{ post.body | safe }}</p>

								<button class="btn btn-main-2 btn-round-full"><a style="color: white;" href="{% url 'post:post_share' post.id %}">Maqolani ulashish</a></button>

							</div>
						</div>
					</div>
					<!-- Commentlar  -->
					<div class="col-lg-12">
						<div class="comment-area mt-4 mb-5">
							<div>
								{% with comments.count as total_comments %}
									{% if total_comments == 0 %}
										<h4 class="mb-4">Hali izohlar mavjud emas</h4>
									{% else %}
										<h4 class="mb-4">{{ total_comments }} ta izoh mavjud</h4>
									{% endif %}
								{% endwith %}
							</div>
							<ul class="comment-tree list-unstyled">
								<li>
									<div class="comment-area-box">

										{% for comment in comments %}
										<div class="comment-info">
											<h5 class="mb-1">{{ comment.name }} | {{ comment.email }}</h5>
											<span class="date-comm">{{ comment.created_at|date:" d-F Y | f" }}</span>
										</div>

										<div class="comment-content mt-3">
											<p>{{ comment.body | safe }}</p>
										</div>
										{% endfor %}

									</div>
								</li>
							</ul>
						</div>
					</div>

					<div>
						{% if new_comment %}
							<h2>Sizning izohingiz qo'shildi</h2>
						{% else %}
							<h2>Izoh qoldirish</h2>
							<form action="." method="post">
								{{  comment_form.media }}
								{{ comment_form | crispy }}
								{% csrf_token %}
								<br>
								<p><input  type="submit" value="Qo'shish"></p>
							</form>
						{% endif %}

						<br>

						<a href="{% url 'post:post_list' %}"><button class="btn btn-main-2 btn-round-full">Ortga</button></a>

					</div>
				</div>
            </div>
            <!-- eng kop postlar -->
            <div class="col-lg-4">
                <div class="sidebar-wrap pl-lg-4 mt-5 mt-lg-0">
					<div class="sidebar-widget latest-post mb-3">
						<h5>Eng so'nngi yangiliklar</h5>
						 
						{% show_lastest_posts %}

					</div>

					<div class="sidebar-widget latest-post mb-3">
						<h5>Eng ko'p ko'rilgan yangiliklar</h5>
						{% most_viewed %}	
				    </div>
				</div>
			</div>
            </div>   
        </div>
    </div>
</section>

	
{% endblock content %}

#

templates/post/share.html
{% extends 'base.html' %} 
{% load static %}


{% block content %} 

    <section class="contact-form-wrap section">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-6">
                    <div class="section-title text-center">
                        {% if sent %}
                            <h2 class="text-md mb-2">Xabar muvaffaqiyatli jo'natildi</h2>
                            <div class="divider mx-auto my-4"></div>
                            <p class="mb-5">{{ post.title }}</p>
                            <p>maqolasi {{ form.cleaned_data.to }} ga yuborildi.</p>
                            <br><br>
                            <button><a href="{% url 'post:post_list' %}">Bosh sahifa </a></button>
                        {% else %}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12">
                    <h1 style="text-align: center;">{{ post.title }} maqolasini ulashish</h1>
                        <form  style="text-align: center;"   method="post">
                             {{ form.as_p }}<!-- as_ul and as_table -->
                             {% csrf_token %}<!-- hafsizlikka javobgar -->
                            <br>
                            <input type="submit" value="Yuborish">
                        </form>
                        <button><a href="{% url 'post:post_list' %}">Ortga</a></button>
                    {% endif %}    
                </div>
            </div>
        </div>
    </section>
    
{% endblock content %}

templates/tags/lastest_posts.html
{% for post in lastest_posts %}

    <h4><a href="{{ post.get_absolute_url }}">{{post.title }}</a></h4>
    <p>{{ post.created_at | date:"d-m-Y f"  }}</p>

{% endfor %}

templates/tags/most_viewed.html
{% for post in most_viewed %}

    <h4><a href="{{ post.get_absolute_url }}">{{post.title }}</a></h4>
    <p>✔{{ post.see }} {{ post.created_at | date:"d-m-Y f"  }}</p>

{% endfor %}